"""add_user_id_to_accounts_and_balances

Revision ID: d4641b3eaeab
Revises: 
Create Date: 2026-01-18 12:04:19.251206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4641b3eaeab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False))
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_unique_constraint('uq_account_user_name', 'accounts', ['user_id', 'name'])
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('balances', sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_index('ix_balances_user_id', 'balances', ['user_id'], unique=False)
    op.create_foreign_key(None, 'balances', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balances', type_='foreignkey')
    op.drop_index('ix_balances_user_id', table_name='balances')
    op.drop_column('balances', 'user_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_constraint('uq_account_user_name', 'accounts', type_='unique')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###
