"""Generates synthetic (non-PII) HDFC-statement-shaped PDF fixtures for tests.

Run directly to regenerate all fixture files:
    uv run python tests/fixtures/generate_hdfc_fixture.py

These are NOT real bank statements — no real account data is used anywhere
in this repo. The layout (transaction table, then a customer-info block with
a bare courtesy-titled name line and no "Name:" label, then a trailing
"STATEMENT SUMMARY :-" table whose last column is the closing balance)
mirrors the structure of a real HDFC net-banking statement PDF, confirmed by
manually inspecting one (outside this repo) while building the parser in
statements/parsers/hdfc.py. All names, addresses, and numbers below are made
up.
"""

from io import BytesIO
from pathlib import Path

from pypdf import PdfReader, PdfWriter
from reportlab.pdfgen import canvas

TEST_PDF_PASSWORD = "Fireons-Test-1234"

FIXTURES_DIR = Path(__file__).parent

TRANSACTION_TABLE_LINES = [
    "Date Narration Chq./Ref.No. Value Dt Withdrawal Amt. Deposit Amt. Closing Balance",
    "01/03/25 UPI-SAMPLE MERCHANT",
    "PAYMENTS-SAMPLE@OKHDFC",
    "0000123456789012 01/03/25 500.00 99500.00",
    "-SAMPLE0001234-123456789012-UPI",
    "15/03/25 NEFT CR-SAMPLE0009999-SAMPLE PAYOUT",
    "SAMPLE0009999 15/03/25 28956.78 128456.78",
    "UT-SAMPLE PERSON",
]

CUSTOMER_INFO_LINES = [
    "Page No .: 1",
    "MR. TEST USER",
    "1-2-3/AB",
    "SAMPLE STREET, SAMPLE AREA",
    "SAMPLE CITY 100001",
    "SAMPLE STATE INDIA",
    "JOINT HOLDERS :",
    "Nomination : Registered",
    "Statement of accountFrom : 01/03/2025 To : 31/03/2025",
    "Account Branch : SAMPLE BRANCH",
    "Address : HDFC BANK LTD, SAMPLE ADDRESS",
    "City : SAMPLE CITY 100001",
    "State : SAMPLE STATE",
    "Currency : INR",
    "Cust ID : 99999999",
    "Account No : 50100123456789 CLASSIC ON PHONE",
    "A/C Open Date : 01/01/2020",
    "Account Status : Regular",
    "RTGS/NEFT IFSC : HDFC0001234 MICR : 100240001",
    "Branch Code : 1234",
    "Account Type : SAVINGS - RESIDENTS(113)",
    "HDFC BANK LIMITED",
    "*Closing balance includes funds earmarked for hold and uncleared funds",
]

STATEMENT_SUMMARY_LINES = [
    "STATEMENT SUMMARY :-",
    "Opening Balance Dr Count Cr Count Debits Credits Closing Bal",
    "100000.00 1 1 500.00 28956.78 128456.78",
    "Generated On: 31-Mar-2025 10:00 Generated By: 99999999 Requesting Branch Code: NET",
]

VALID_STATEMENT_LINES = (
    TRANSACTION_TABLE_LINES + CUSTOMER_INFO_LINES + STATEMENT_SUMMARY_LINES
)

# No STATEMENT SUMMARY block at all, and the transaction table's own
# "Closing Balance" column header never has an amount within its search
# window — so no closing balance can be found anywhere in this fixture.
MISSING_BALANCE_LINES = TRANSACTION_TABLE_LINES + CUSTOMER_INFO_LINES

LARGE_AMOUNT_LINES = (
    TRANSACTION_TABLE_LINES
    + CUSTOMER_INFO_LINES
    + [
        "STATEMENT SUMMARY :-",
        "Opening Balance Dr Count Cr Count Debits Credits Closing Bal",
        "1000000.00 1 1 500.00 1234567.89 12,34,567.89",
        "Generated On: 31-Mar-2025 10:00 Generated By: 99999999 Requesting Branch Code: NET",
    ]
)

OTHER_BANK_LINES = [
    "ICICI BANK LIMITED",
    "Account Statement",
    "",
    "Customer Name: TEST USER",
    "Statement Period: March 2025",
    "",
    "This statement format is intentionally unrelated to HDFC's layout.",
]


def _render_pdf_bytes(lines: list[str]) -> bytes:
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=(595, 842))
    y = 800
    for line in lines:
        pdf.drawString(50, y, line)
        y -= 18
    pdf.save()
    return buffer.getvalue()


def _write_encrypted(lines: list[str], password: str, path: Path) -> None:
    plain_bytes = _render_pdf_bytes(lines)
    reader = PdfReader(BytesIO(plain_bytes))
    writer = PdfWriter()
    for page in reader.pages:
        writer.add_page(page)
    writer.encrypt(user_password=password)
    with open(path, "wb") as fh:
        writer.write(fh)


def _write_plain(lines: list[str], path: Path) -> None:
    path.write_bytes(_render_pdf_bytes(lines))


def generate_all() -> None:
    _write_encrypted(
        VALID_STATEMENT_LINES, TEST_PDF_PASSWORD, FIXTURES_DIR / "hdfc_statement_valid.pdf"
    )
    _write_encrypted(
        MISSING_BALANCE_LINES,
        TEST_PDF_PASSWORD,
        FIXTURES_DIR / "hdfc_statement_missing_balance.pdf",
    )
    _write_encrypted(
        LARGE_AMOUNT_LINES,
        TEST_PDF_PASSWORD,
        FIXTURES_DIR / "hdfc_statement_large_amount.pdf",
    )
    _write_plain(OTHER_BANK_LINES, FIXTURES_DIR / "other_bank_statement.pdf")
    (FIXTURES_DIR / "not_a_pdf.txt").write_bytes(b"This is not a PDF file.\n")


if __name__ == "__main__":
    generate_all()
    print(f"Fixtures written to {FIXTURES_DIR}")
